spring:
  application:
    name: notification-application

#  rabbitmq:
#    host: ${RABBIT_HOST:localhost}
#    port: ${RABBIT_PORT:5672}
#    username: ${RABBIT_USER:guest}
#    password: ${RABBIT_PASSWORD:guest}
#    virtual-host: ${RABBIT_VHOST:/}
#    connection-timeout: 30000
  cloud:
    function:
      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking


server:
  port:
    8084