spring:
  application:
    name: product-application
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: inferio
    password: inferio
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
