#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: product-service
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/products/**
#          filters:
#            - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
#
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
#
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/orders/** , /cart/**
#          filters:
#            - "RewritePath=/(?<segment>/?.*),/api/${segment}"
#
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - SetPath=/
#
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**
#
#
#logging:
#  level:
#    root: INFO
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE
#

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

#circuit breaker config
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/ecom-app

server:
  port: 8080
